export const ChainSelect = [
  {
    label: "Ethereum",
    value: "homestead",
    description: "Ethereum Network Mainnet",
    icon: "/icon/eth.svg",
    chainId: 1,
    L0ChainId: 101,
  },
  {
    label: "Polygon",
    value: "matic",
    description: "Polygon Network Mainnet",
    icon: "/icon/polygon.svg",
    chainId: 137,
    L0ChainId: 109,
  },
  {
    label: "Optimism",
    value: "optimism",
    description: "Optimism Network Mainnet",
    icon: "/icon/optimism.svg",
    chainId: 10,
    L0ChainId: 111,
  },
  {
    label: "Arbitrum",
    value: "arbitrum",
    description: "Arbitrum Network Mainnet",
    icon: "/icon/arbitrum.svg",
    chainId: 42161,
    L0ChainId: 110,
  },
  {
    label: "Base",
    value: "base",
    description: "Base Network Mainnet",
    icon: "/icon/base.png",
    chainId: 8453,
    L0ChainId: 184,
  },
  {
    label: "BNB Chain",
    value: "bsc",
    description: "BSC Network Mainnet",
    icon: "/icon/bnb.svg",
    chainId: 56,
    L0ChainId: 102,
  },
  {
    label: "Canto",
    value: "canto",
    description: "Canto Network Mainnet",
    icon: "/icon/canto.svg",
    chainId: 7700,
    L0ChainId: 159,
  },
];
